{% set name = "caddie" %}
{% set version = "0.0.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/vkvam/caddie

build:
  number: 0
  script: "$PYTHON -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pythonocc-core==7.7.2
  build:
    - python
test:
  imports:
    - caddie

about:
  home: https://github.com/vkvam/caddie
  license: GPLv3
  license_family: GPL3
  license_file: LICENSE
  summary: CAD library with python-occ backend focused on simplicity and efficiency

extra:
  recipe-maintainers:
    - bananfluejegeren
