{% set name = "caddie" %}
{% set version = "0.0.5" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/vkvam/caddie

build:
  number: 0
  script: "$PYTHON setup.py install"  # If you're using setup.py

requirements:
  host:
    - python
    - pip
  build:
    - python
    - setuptools
  run:
    - python
    - pythonocc-core ==7.7.2
test:
  imports:
    - caddie

about:
  home: https://github.com/vkvam/caddie
  license: AGPLv3
  license_file: LICENSE
  summary: CAD library with python-occ backend focused on simplicity and efficiency

extra:
  recipe-maintainers:
    - bananfluejegeren
