name: Conda Build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.10.11, 3.11.9, 3.12.3]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          activate-environment: test-env
          environment-file: environment.yml
          use-mamba: true

      - name: Install conda-build
        run: |
          conda install -y conda-build anaconda-client

      - name: Build and upload the package
        run: |
          conda config --set anaconda_upload yes
          conda build . --user ${{ secrets.ANACONDA_USERNAME }} --token ${{ secrets.ANACONDA_TOKEN }}

#      - name: Upload package to Anaconda.org
#        run: |
#          anaconda upload /path/to/your/package.tar.bz2

